services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./src:/app/src
    ports:
      - 4200:4200

  api:
    image: lichodev/fvl-api
    ports:
      - 3000:3000
    environment:
      - DB_HOST=database
      - DB_NAME=db_fvl
      - DB_PASSWORD=segura123!
      - DB_PORT=5432
      - DB_USER=fvl

  database:
    image: postgres:latest
    volumes:
      - pg_data:/var/lib/postgresql/data/pgdata
    environment:
      - POSTGRES_USER=fvl
      - POSTGRES_PASSWORD=segura123!
      - POSTGRES_DB=db_fvl
      - PGDATA=/var/lib/postgresql/data/pgdata

volumes:
  pg_data:
