apiVersion: apps/v1
kind: Deployment
metadata:
  name: fvl-angular
  namespace: fvl-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: fvl-angular
  template:
    metadata:
      labels:
        app: fvl-angular
    spec:
      containers:
        - name: fvl-angular
          image: lichodev/fvl-angular
          env:
            - name: API_URL
              value: http://192.168.59.103:30001
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: fvl-angular
  namespace: fvl-app
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30000
  selector:
    app: fvl-angular
